name = "clever_030_is_prime"
version = "0.1.0"
defaultTargets = ["clever_030_is_prime"]

[[lean_lib]]
name = "clever_030_is_prime"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"
