name = "next_code_point_reverse_u8"
version = "0.1.0"
defaultTargets = ["next_code_point_reverse_u8", "Next_code_point_reverse_u8Obligations"]

[[lean_lib]]
name = "next_code_point_reverse_u8"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Next_code_point_reverse_u8Obligations"
