name = "abs_diff_i64"
version = "0.1.0"
defaultTargets = ["abs_diff_i64", "Abs_diff_i64Obligations"]

[[lean_lib]]
name = "abs_diff_i64"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Abs_diff_i64Obligations"
