name = "clever_034_max_element"
version = "0.1.0"
defaultTargets = ["clever_034_max_element"]

[[lean_lib]]
name = "clever_034_max_element"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"
