name = "align_to_usize"
version = "0.1.0"
defaultTargets = ["align_to_usize", "Align_to_usizeObligations"]

[[lean_lib]]
name = "align_to_usize"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Align_to_usizeObligations"
