name = "clever_082_starts_one_ends"
version = "0.1.0"
defaultTargets = ["clever_082_starts_one_ends", "Clever_082_starts_one_endsObligations"]

[[lean_lib]]
name = "clever_082_starts_one_ends"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Clever_082_starts_one_endsObligations"
