name = "clever_008_sum_product"
version = "0.1.0"
defaultTargets = ["clever_008_sum_product", "Clever_008_sum_productObligations"]

[[lean_lib]]
name = "clever_008_sum_product"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Clever_008_sum_productObligations"
