name = "clever_048_modp"
version = "0.1.0"
defaultTargets = ["clever_048_modp"]

[[lean_lib]]
name = "clever_048_modp"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"
