name = "repeat_usize"
version = "0.1.0"
defaultTargets = ["repeat_usize", "Repeat_usizeObligations"]

[[lean_lib]]
name = "repeat_usize"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Repeat_usizeObligations"
