name = "clever_070_triangle_area"
version = "0.1.0"
defaultTargets = ["clever_070_triangle_area", "Clever_070_triangle_areaObligations"]

[[lean_lib]]
name = "clever_070_triangle_area"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Clever_070_triangle_areaObligations"
