name = "big_endian_write_u64"
version = "0.1.0"
defaultTargets = ["big_endian_write_u64", "Big_endian_write_u64Obligations"]

[[lean_lib]]
name = "big_endian_write_u64"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Big_endian_write_u64Obligations"
