name = "clever_144_specialFilter"
version = "0.1.0"
defaultTargets = ["clever_144_specialFilter"]

[[lean_lib]]
name = "clever_144_specialFilter"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"
