name = "min"
version = "0.1.0"
defaultTargets = ["min", "MinObligations"]

[[lean_lib]]
name = "min"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "MinObligations"
