name = "is_zero"
version = "0.1.0"
defaultTargets = ["is_zero", "Is_zeroObligations"]

[[lean_lib]]
name = "is_zero"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Is_zeroObligations"
