name = "clever_155_right_angle_triangle"
version = "0.1.0"
defaultTargets = ["clever_155_right_angle_triangle"]

[[lean_lib]]
name = "clever_155_right_angle_triangle"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"
