name = "recursion_handmade"
version = "0.1.0"
defaultTargets = ["recursion_handmade", "RecursionObligations"]

[[lean_lib]]
name = "recursion_handmade"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "RecursionObligations"
