name = "clever_091_any_int"
version = "0.1.0"
defaultTargets = ["clever_091_any_int", "Clever_091_any_intObligations"]

[[lean_lib]]
name = "clever_091_any_int"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Clever_091_any_intObligations"
