name = "clever_040_car_race_collision"
version = "0.1.0"
defaultTargets = ["clever_040_car_race_collision", "Clever_040_car_race_collisionObligations"]

[[lean_lib]]
name = "clever_040_car_race_collision"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Clever_040_car_race_collisionObligations"
