name = "clever_058_largest_prime_factor"
version = "0.1.0"
defaultTargets = ["clever_058_largest_prime_factor"]

[[lean_lib]]
name = "clever_058_largest_prime_factor"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"
