name = "while_handmade"
version = "0.1.0"
defaultTargets = ["while_handmade", "WhileObligations"]

[[lean_lib]]
name = "while_handmade"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "WhileObligations"
