name = "clever_047_sum_to_n"
version = "0.1.0"
defaultTargets = ["clever_047_sum_to_n"]

[[lean_lib]]
name = "clever_047_sum_to_n"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"
