name = "clever_050_monotonic"
version = "0.1.0"
defaultTargets = ["clever_050_monotonic"]

[[lean_lib]]
name = "clever_050_monotonic"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"
