name = "clever_114_max_fill_count"
version = "0.1.0"
defaultTargets = ["clever_114_max_fill_count", "Clever_114_max_fill_countObligations"]

[[lean_lib]]
name = "clever_114_max_fill_count"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Clever_114_max_fill_countObligations"
