name = "clever_020_find_closest_elements"
version = "0.1.0"
defaultTargets = ["clever_020_find_closest_elements", "Clever_020_find_closest_elementsObligations"]

[[lean_lib]]
name = "clever_020_find_closest_elements"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Clever_020_find_closest_elementsObligations"
