[package]
name = "nth_root_u64"
version = "0.1.0"
edition = "2024"

[dependencies]
hax-lib = "0.3.6"

[package.metadata.extracted_from]
crate = "num-integer"
version = "0.1.46"
function = "nth_root"
type = "u64"
function_path = "num_integer::nth_root"
