name = "clever_089_next_smallest"
version = "0.1.0"
defaultTargets = ["clever_089_next_smallest"]

[[lean_lib]]
name = "clever_089_next_smallest"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"
