name = "clever_067_pluck"
version = "0.1.0"
defaultTargets = ["clever_067_pluck"]

[[lean_lib]]
name = "clever_067_pluck"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"
