name = "chacha20"
version = "0.1.0"
defaultTargets = ["chacha20", "Chacha20Obligations"]

[[lean_lib]]
name = "chacha20"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Chacha20Obligations"
