name = "clever_042_pairs_sum_to_zero"
version = "0.1.0"
defaultTargets = ["clever_042_pairs_sum_to_zero"]

[[lean_lib]]
name = "clever_042_pairs_sum_to_zero"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"
