name = "clever_056_monotonic"
version = "0.1.0"
defaultTargets = ["clever_056_monotonic", "Clever_056_monotonicObligations"]

[[lean_lib]]
name = "clever_056_monotonic"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Clever_056_monotonicObligations"
