name = "clever_120_solution"
version = "0.1.0"
defaultTargets = ["clever_120_solution"]

[[lean_lib]]
name = "clever_120_solution"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"
