name = "clever_137_special_factorial"
version = "0.1.0"
defaultTargets = ["clever_137_special_factorial"]

[[lean_lib]]
name = "clever_137_special_factorial"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"
