name = "clever_121_add_elements"
version = "0.1.0"
defaultTargets = ["clever_121_add_elements", "Clever_121_add_elementsObligations"]

[[lean_lib]]
name = "clever_121_add_elements"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Clever_121_add_elementsObligations"
