name = "clever_046_median"
version = "0.1.0"
defaultTargets = ["clever_046_median", "Clever_046_medianObligations"]

[[lean_lib]]
name = "clever_046_median"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Clever_046_medianObligations"
