name = "clever_021_rescale_to_unit"
version = "0.1.0"
defaultTargets = ["clever_021_rescale_to_unit"]

[[lean_lib]]
name = "clever_021_rescale_to_unit"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"
