name = "max_size_for_align_usize"
version = "0.1.0"
defaultTargets = ["max_size_for_align_usize", "Max_size_for_align_usizeObligations"]

[[lean_lib]]
name = "max_size_for_align_usize"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Max_size_for_align_usizeObligations"
