name = "clever_025_remove_duplicates"
version = "0.1.0"
defaultTargets = ["clever_025_remove_duplicates", "Clever_025_remove_duplicatesObligations"]

[[lean_lib]]
name = "clever_025_remove_duplicates"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Clever_025_remove_duplicatesObligations"
