name = "clever_152_cycpattern_check"
version = "0.1.0"
defaultTargets = ["clever_152_cycpattern_check", "Clever_152_cycpattern_checkObligations"]

[[lean_lib]]
name = "clever_152_cycpattern_check"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Clever_152_cycpattern_checkObligations"
