name = "from_ref_u64"
version = "0.1.0"
defaultTargets = ["from_ref_u64", "From_ref_u64Obligations"]

[[lean_lib]]
name = "from_ref_u64"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "From_ref_u64Obligations"
