name = "clever_029_get_positive"
version = "0.1.0"
defaultTargets = ["clever_029_get_positive", "Clever_029_get_positiveObligations"]

[[lean_lib]]
name = "clever_029_get_positive"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Clever_029_get_positiveObligations"
