name = "clever_032_sort_third"
version = "0.1.0"
defaultTargets = ["clever_032_sort_third"]

[[lean_lib]]
name = "clever_032_sort_third"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"
