name = "rsplit_array_mut_u64"
version = "0.1.0"
defaultTargets = ["rsplit_array_mut_u64", "Rsplit_array_mut_u64Obligations"]

[[lean_lib]]
name = "rsplit_array_mut_u64"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Rsplit_array_mut_u64Obligations"
