name = "clever_119_maximum"
version = "0.1.0"
defaultTargets = ["clever_119_maximum", "Clever_119_maximumObligations"]

[[lean_lib]]
name = "clever_119_maximum"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Clever_119_maximumObligations"
