name = "clever_009_rolling_max"
version = "0.1.0"
defaultTargets = ["clever_009_rolling_max", "Clever_009_rolling_maxObligations"]

[[lean_lib]]
name = "clever_009_rolling_max"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Clever_009_rolling_maxObligations"
