name = "clever_057_common"
version = "0.1.0"
defaultTargets = ["clever_057_common", "Clever_057_commonObligations"]

[[lean_lib]]
name = "clever_057_common"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Clever_057_commonObligations"
