name = "clever_107_count_nums"
version = "0.1.0"
defaultTargets = ["clever_107_count_nums"]

[[lean_lib]]
name = "clever_107_count_nums"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"
