name = "clever_129_tri"
version = "0.1.0"
defaultTargets = ["clever_129_tri", "Clever_129_triObligations"]

[[lean_lib]]
name = "clever_129_tri"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Clever_129_triObligations"
