[package]
name = "big_endian_write_u64_into"
version = "0.1.0"
edition = "2024"

[package.metadata.extracted_from]
crate = "byteorder"
version = "1.5.0"
function = "write_u64_into"
impl_type = "BigEndian"
impl_trait = "ByteOrder"
function_path = "byteorder::BigEndian::write_u64_into"

[dependencies]
hax-lib = "0.3.6"
