name = "clever_149_double_the_difference"
version = "0.1.0"
defaultTargets = ["clever_149_double_the_difference", "Clever_149_double_the_differenceObligations"]

[[lean_lib]]
name = "clever_149_double_the_difference"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Clever_149_double_the_differenceObligations"
