name = "clever_145_get_max_triples"
version = "0.1.0"
defaultTargets = ["clever_145_get_max_triples", "Clever_145_get_max_triplesObligations"]

[[lean_lib]]
name = "clever_145_get_max_triples"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Clever_145_get_max_triplesObligations"
