name = "recursion_example"
version = "0.1.0"
defaultTargets = ["recursion_example", "Recursion_exampleObligations"]

[[lean_lib]]
name = "recursion_example"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Recursion_exampleObligations"
