name = "square"
version = "0.1.0"
defaultTargets = ["square"]

[[lean_lib]]
name = "square"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"