name = "clever_135_largest_smallest_integers"
version = "0.1.0"
defaultTargets = ["clever_135_largest_smallest_integers", "Clever_135_largest_smallest_integersObligations"]

[[lean_lib]]
name = "clever_135_largest_smallest_integers"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Clever_135_largest_smallest_integersObligations"
