name = "apply_twice"
version = "0.1.0"
defaultTargets = ["apply_twice"]

[[lean_lib]]
name = "apply_twice"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"
