name = "clever_084_solve"
version = "0.1.0"
defaultTargets = ["clever_084_solve", "Clever_084_solveObligations"]

[[lean_lib]]
name = "clever_084_solve"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Clever_084_solveObligations"
