name = "clever_052_add"
version = "0.1.0"
defaultTargets = ["clever_052_add", "Clever_052_addObligations"]

[[lean_lib]]
name = "clever_052_add"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Clever_052_addObligations"
