name = "padding_needed_for_usize"
version = "0.1.0"
defaultTargets = ["padding_needed_for_usize", "Padding_needed_for_usizeObligations"]

[[lean_lib]]
name = "padding_needed_for_usize"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Padding_needed_for_usizeObligations"
