name = "clever_074_is_multiply_prime"
version = "0.1.0"
defaultTargets = ["clever_074_is_multiply_prime", "Clever_074_is_multiply_primeObligations"]

[[lean_lib]]
name = "clever_074_is_multiply_prime"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Clever_074_is_multiply_primeObligations"
