name = "clamp"
version = "0.1.0"
defaultTargets = ["clamp", "ClampObligations"]

[[lean_lib]]
name = "clamp"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "ClampObligations"
