name = "clever_005_intersperse"
version = "0.1.0"
defaultTargets = ["clever_005_intersperse", "Clever_005_intersperseObligations"]

[[lean_lib]]
name = "clever_005_intersperse"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Clever_005_intersperseObligations"
