name = "clever_039_triples_sum_to_zero"
version = "0.1.0"
defaultTargets = ["clever_039_triples_sum_to_zero", "Clever_039_triples_sum_to_zeroObligations"]

[[lean_lib]]
name = "clever_039_triples_sum_to_zero"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Clever_039_triples_sum_to_zeroObligations"
