name = "clever_041_incr_list"
version = "0.1.0"
defaultTargets = ["clever_041_incr_list", "Clever_041_incr_listObligations"]

[[lean_lib]]
name = "clever_041_incr_list"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Clever_041_incr_listObligations"
