name = "clever_035_fizz_buzz"
version = "0.1.0"
defaultTargets = ["clever_035_fizz_buzz", "Clever_035_fizz_buzzObligations"]

[[lean_lib]]
name = "clever_035_fizz_buzz"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Clever_035_fizz_buzzObligations"
