name = "clever_136_is_equal_to_sum_even"
version = "0.1.0"
defaultTargets = ["clever_136_is_equal_to_sum_even"]

[[lean_lib]]
name = "clever_136_is_equal_to_sum_even"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"
