name = "clever_134_can_arrange"
version = "0.1.0"
defaultTargets = ["clever_134_can_arrange"]

[[lean_lib]]
name = "clever_134_can_arrange"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"
