name = "clever_068_search"
version = "0.1.0"
defaultTargets = ["clever_068_search"]

[[lean_lib]]
name = "clever_068_search"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"
