name = "while_example"
version = "0.1.0"
defaultTargets = ["while_example", "While_exampleObligations"]

[[lean_lib]]
name = "while_example"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "While_exampleObligations"
