name = "trailing_zeros_u64"
version = "0.1.0"
defaultTargets = ["trailing_zeros_u64", "Trailing_zeros_u64Obligations"]

[[lean_lib]]
name = "trailing_zeros_u64"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Trailing_zeros_u64Obligations"
