name = "little_endian_write_u64_into"
version = "0.1.0"
defaultTargets = ["little_endian_write_u64_into", "Little_endian_write_u64_intoObligations"]

[[lean_lib]]
name = "little_endian_write_u64_into"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Little_endian_write_u64_intoObligations"
