name = "testing_crate"
version = "0.1.0"
defaultTargets = ["testing_crate"]

[[lean_lib]]
name = "testing_crate"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"
