name = "clever_002_truncate_number"
version = "0.1.0"
defaultTargets = ["clever_002_truncate_number", "Clever_002_truncate_numberObligations"]

[[lean_lib]]
name = "clever_002_truncate_number"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Clever_002_truncate_numberObligations"
