name = "is_size_align_valid_usize"
version = "0.1.0"
defaultTargets = ["is_size_align_valid_usize", "Is_size_align_valid_usizeObligations"]

[[lean_lib]]
name = "is_size_align_valid_usize"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Is_size_align_valid_usizeObligations"
