[package]
name = "utf8_first_byte_u8"
version = "0.1.0"
edition = "2024"

[package.metadata.extracted_from]
crate = "core"
version = "0.0.0"
function = "utf8_first_byte"
type = "u8"
function_path = "core::str::validations::utf8_first_byte"

[dependencies]
hax-lib = "0.3.6"

[dev-dependencies]
proptest = "1"
