name = "clever_143_order_by_points"
version = "0.1.0"
defaultTargets = ["clever_143_order_by_points", "Clever_143_order_by_pointsObligations"]

[[lean_lib]]
name = "clever_143_order_by_points"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Clever_143_order_by_pointsObligations"
