name = "clever_071_will_it_fly"
version = "0.1.0"
defaultTargets = ["clever_071_will_it_fly", "Clever_071_will_it_flyObligations"]

[[lean_lib]]
name = "clever_071_will_it_fly"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Clever_071_will_it_flyObligations"
