name = "max_odd_part"
version = "0.1.0"
defaultTargets = ["max_odd_part", "Max_odd_partObligations"]

[[lean_lib]]
name = "max_odd_part"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Max_odd_partObligations"
