name = "contains_u64"
version = "0.1.0"
defaultTargets = ["contains_u64", "Contains_u64Obligations"]

[[lean_lib]]
name = "contains_u64"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Contains_u64Obligations"
