name = "clever_130_digits"
version = "0.1.0"
defaultTargets = ["clever_130_digits", "Clever_130_digitsObligations"]

[[lean_lib]]
name = "clever_130_digits"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Clever_130_digitsObligations"
