name = "big_endian_write_u64_into"
version = "0.1.0"
defaultTargets = ["big_endian_write_u64_into", "Big_endian_write_u64_intoObligations"]

[[lean_lib]]
name = "big_endian_write_u64_into"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Big_endian_write_u64_intoObligations"
