name = "clever_095_count_up_to"
version = "0.1.0"
defaultTargets = ["clever_095_count_up_to", "Clever_095_count_up_toObligations"]

[[lean_lib]]
name = "clever_095_count_up_to"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Clever_095_count_up_toObligations"
