name = "clever_103_unique_digits"
version = "0.1.0"
defaultTargets = ["clever_103_unique_digits"]

[[lean_lib]]
name = "clever_103_unique_digits"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"
