name = "utf8_acc_cont_byte_u32"
version = "0.1.0"
defaultTargets = ["utf8_acc_cont_byte_u32", "Utf8_acc_cont_byte_u32Obligations"]

[[lean_lib]]
name = "utf8_acc_cont_byte_u32"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Utf8_acc_cont_byte_u32Obligations"
