name = "clever_125_is_sorted"
version = "0.1.0"
defaultTargets = ["clever_125_is_sorted"]

[[lean_lib]]
name = "clever_125_is_sorted"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"
