name = "clever_062_fibfib"
version = "0.1.0"
defaultTargets = ["clever_062_fibfib", "Clever_062_fibfibObligations"]

[[lean_lib]]
name = "clever_062_fibfib"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Clever_062_fibfibObligations"
