name = "clever_087_sort_array"
version = "0.1.0"
defaultTargets = ["clever_087_sort_array", "Clever_087_sort_arrayObligations"]

[[lean_lib]]
name = "clever_087_sort_array"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Clever_087_sort_arrayObligations"
