name = "clever_000_has_close_elements"
version = "0.1.0"
defaultTargets = ["clever_000_has_close_elements"]

[[lean_lib]]
name = "clever_000_has_close_elements"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"
