name = "clever_045_fib4"
version = "0.1.0"
defaultTargets = ["clever_045_fib4", "Clever_045_fib4Obligations"]

[[lean_lib]]
name = "clever_045_fib4"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Clever_045_fib4Obligations"
