name = "clever_101_choose_num"
version = "0.1.0"
defaultTargets = ["clever_101_choose_num"]

[[lean_lib]]
name = "clever_101_choose_num"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"
