name = "clever_023_largest_divisor"
version = "0.1.0"
defaultTargets = ["clever_023_largest_divisor", "Clever_023_largest_divisorObligations"]

[[lean_lib]]
name = "clever_023_largest_divisor"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Clever_023_largest_divisorObligations"
