name = "clever_051_median"
version = "0.1.0"
defaultTargets = ["clever_051_median"]

[[lean_lib]]
name = "clever_051_median"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"
