name = "clever_160_generate_integers"
version = "0.1.0"
defaultTargets = ["clever_160_generate_integers"]

[[lean_lib]]
name = "clever_160_generate_integers"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"
