name = "clever_096_multiply"
version = "0.1.0"
defaultTargets = ["clever_096_multiply", "Clever_096_multiplyObligations"]

[[lean_lib]]
name = "clever_096_multiply"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Clever_096_multiplyObligations"
