name = "clever_157_eat"
version = "0.1.0"
defaultTargets = ["clever_157_eat"]

[[lean_lib]]
name = "clever_157_eat"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"
