name = "clever_038_prime_fib"
version = "0.1.0"
defaultTargets = ["clever_038_prime_fib"]

[[lean_lib]]
name = "clever_038_prime_fib"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"
