name = "while_count_up"
version = "0.1.0"
defaultTargets = ["while_count_up", "While_count_upObligations"]

[[lean_lib]]
name = "while_count_up"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "While_count_upObligations"
