name = "clever_069_strange_sort_list"
version = "0.1.0"
defaultTargets = ["clever_069_strange_sort_list"]

[[lean_lib]]
name = "clever_069_strange_sort_list"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"
