name = "gcd_rec"
version = "0.1.0"
defaultTargets = ["gcd_rec"]

[[lean_lib]]
name = "gcd_rec"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"
