name = "clever_072_smallest_change"
version = "0.1.0"
defaultTargets = ["clever_072_smallest_change"]

[[lean_lib]]
name = "clever_072_smallest_change"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"
