name = "clever_132_sum_squares"
version = "0.1.0"
defaultTargets = ["clever_132_sum_squares", "Clever_132_sum_squaresObligations"]

[[lean_lib]]
name = "clever_132_sum_squares"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Clever_132_sum_squaresObligations"
