name = "clever_004_mean_absolute_deviation"
version = "0.1.0"
defaultTargets = ["clever_004_mean_absolute_deviation"]

[[lean_lib]]
name = "clever_004_mean_absolute_deviation"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"
