name = "clever_013_greatest_common_divisor"
version = "0.1.0"
defaultTargets = ["clever_013_greatest_common_divisor"]

[[lean_lib]]
name = "clever_013_greatest_common_divisor"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"
