name = "clever_148_x_or_y"
version = "0.1.0"
defaultTargets = ["clever_148_x_or_y", "Clever_148_x_or_yObligations"]

[[lean_lib]]
name = "clever_148_x_or_y"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Clever_148_x_or_yObligations"
