name = "clever_122_get_odd_collatz"
version = "0.1.0"
defaultTargets = ["clever_122_get_odd_collatz"]

[[lean_lib]]
name = "clever_122_get_odd_collatz"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"
