name = "clever_033_unique"
version = "0.1.0"
defaultTargets = ["clever_033_unique"]

[[lean_lib]]
name = "clever_033_unique"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"
