name = "count_to"
version = "0.1.0"
defaultTargets = ["count_to", "Count_toObligations"]

[[lean_lib]]
name = "count_to"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Count_toObligations"
