name = "clever_106_even_odd_palindrome"
version = "0.1.0"
defaultTargets = ["clever_106_even_odd_palindrome", "Clever_106_even_odd_palindromeObligations"]

[[lean_lib]]
name = "clever_106_even_odd_palindrome"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Clever_106_even_odd_palindromeObligations"
