name = "clever_113_minSubArraySum"
version = "0.1.0"
defaultTargets = ["clever_113_minSubArraySum", "Clever_113_minSubArraySumObligations"]

[[lean_lib]]
name = "clever_113_minSubArraySum"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Clever_113_minSubArraySumObligations"
