name = "gcd_while"
version = "0.1.0"
defaultTargets = ["gcd_while", "Gcd_whileObligations"]

[[lean_lib]]
name = "gcd_while"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Gcd_whileObligations"
