name = "clever_046_add_two"
version = "0.1.0"
defaultTargets = ["clever_046_add_two"]

[[lean_lib]]
name = "clever_046_add_two"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"
