name = "clever_150_compare"
version = "0.1.0"
defaultTargets = ["clever_150_compare"]

[[lean_lib]]
name = "clever_150_compare"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"
