name = "clever_127_prod_signs"
version = "0.1.0"
defaultTargets = ["clever_127_prod_signs"]

[[lean_lib]]
name = "clever_127_prod_signs"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"
