name = "utf8_is_cont_byte_u8"
version = "0.1.0"
defaultTargets = ["utf8_is_cont_byte_u8", "Utf8_is_cont_byte_u8Obligations"]

[[lean_lib]]
name = "utf8_is_cont_byte_u8"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Utf8_is_cont_byte_u8Obligations"
