name = "clever_099_make_a_pile"
version = "0.1.0"
defaultTargets = ["clever_099_make_a_pile"]

[[lean_lib]]
name = "clever_099_make_a_pile"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"
