name = "factorial"
version = "0.1.0"
defaultTargets = ["factorial", "FactorialObligations"]

[[lean_lib]]
name = "factorial"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "FactorialObligations"
