name = "clever_059_sum_to_n"
version = "0.1.0"
defaultTargets = ["clever_059_sum_to_n", "Clever_059_sum_to_nObligations"]

[[lean_lib]]
name = "clever_059_sum_to_n"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Clever_059_sum_to_nObligations"
