name = "size_rounded_up_to_custom_align_usize"
version = "0.1.0"
defaultTargets = ["size_rounded_up_to_custom_align_usize", "Size_rounded_up_to_custom_align_usizeObligations"]

[[lean_lib]]
name = "size_rounded_up_to_custom_align_usize"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Size_rounded_up_to_custom_align_usizeObligations"
