name = "clever_075_is_simple_power"
version = "0.1.0"
defaultTargets = ["clever_075_is_simple_power", "Clever_075_is_simple_powerObligations"]

[[lean_lib]]
name = "clever_075_is_simple_power"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Clever_075_is_simple_powerObligations"
