name = "as_slice_u64"
version = "0.1.0"
defaultTargets = ["as_slice_u64", "As_slice_u64Obligations"]

[[lean_lib]]
name = "as_slice_u64"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "As_slice_u64Obligations"
