name = "pad_to_align_usize"
version = "0.1.0"
defaultTargets = ["pad_to_align_usize", "Pad_to_align_usizeObligations"]

[[lean_lib]]
name = "pad_to_align_usize"

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"

[[lean_lib]]
name = "Pad_to_align_usizeObligations"
